language: generic
addons:
  apt:
    update: true
matrix:
  include:
  - name: Python 3.5 - 3.8 manylinux
    os: linux
    dist: xenial
    before_install:
    - sudo apt-get install -y python3 python3-dev python3-pip
    - sudo python3 -m pip install twine
    sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64 PLAT=manylinux2014_x86_64
    install:
    - docker pull $DOCKER_IMAGE
    script:
    - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/ci/travis_build_wheels.sh
    - ls dist/
    deploy:
      provider: script
      script: python3 -m twine upload dist/*
      on:
        tags: true
  - name: Python 3.8 sdist
    os: linux
    language: python
    dist: xenial
    python: '3.8'
    before_install:
      - sudo apt-get install -y libdrm-dev
    install:
    - pip install cython twine
    script:
    - python setup.py bdist_wheel
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: 3Ow6nZipEVmTyessG7oeI8rSGtX5vTWMCVOgoz2fCeoFZ8PYCR0YYabo8H7x43jeE2zt85UE/5M5oT0wIzyNYvvN1Xv2gvLCJotjiXa3rbycf8S7p8XQ8OsICMcu1H3zj5uxFEoNpiQOCqyUbXW/hYdQsRH3YcBtc2oHvTNYoHKUWD/qdf9zMRrKkr1/K+D9TboIhvrXmSRJ4X2NmOsFAucHxEHiVy3r+1NNt/kvexQPAbCJ1noRSKhkj+MqOs3vM1V5sNDF0UrEbIpQOtfXudEGtqo4wPAUYIKZ5XZ8MdVehAzPDP9B/3uD6ba6mlzYpbLDjxh+fERCVinqrsma+wovE9qy8rMn2FKAzW+1ghnewEtnjI1qpDV6UPKojWGZIADVVNarMVrHz+T5MUyDR7IwR6EB1lF1W1hZ8YiQpRY8a2YuhzYzjL7jPkOiG34UjwkqJagOTHQzHWFbg5HJi9UY5Zzc+xB7soxg7dTyCRBRugOKvI4NDxMjttBwRmzUudliRs6n5CjLhZWQYsTQFYNDAr4mRvhxtRrh0IdZ8dTG3S7l5+O/MyzJzaPNf8gUpiBZjQdbd92oqXl25BiTxbOQPRMYwifKRYaHO/a368i3fUvfgsmzXtTP69Olpy/usQM7GrgGWS2rieTQkSXqao2rf794LsQIIg41YwS2jf0=
      on:
        tags: true
      distributions: sdist
      skip_existing: true
git:
  depth: 1
env:
  global:
    - TWINE_USERNAME: __token__
    - secure: rlJvdXG1Z0xOvi4f7CdEZYx/HQQOYvEDxaAHHC06mGhSM523iwOdQEv2SwgSzWOz3ige44l7mIDqJ5lNjMHjM6u5MAHTTMFHLESMG/r1rfRiBeypFRyDixs0O/dMEchwWzVv3+7tMeX+if3ts9j8tM8SxNqs+OnIAnwtAxQVhkRWXnnn+SvXJ8QUVvdZ0jwTYynXjU77IcREXXov6aVqzR55UQG3zPmVE77GTlPXlFZczrfenG9R7kctfR+7+wE32ri1RhXEdADugQrF97EQ8TObji0vlsuW6AjC7qq45AHDRUgFM4N/d41dEOMuBPYmXl2t7kOqtviLaYxhF9OyCtOiyef4r8QcyYg/goRsM6xn0hfLGt9KeotD4YjAX06WhpEaiFB9zkShk0yO0yoZm6kYiXluTS7tajX9n0xUdZQipIGmAmaj3tSo+AkZpQTjtIJv9li7d6tec0oEV5rK2tCLj4y2gye1sxxDHObd37d4kZWTVJw7FaQH+We27vVNKlVTGVKaTHdKRgHYdL+J7BXInS1/moI+e7KMoRqxLUNKUXLqz/mrbsUl843NEUjzNfni8ttviPUlXgtM9gNx04Ftg+X1As3uUjzGg115HbEX9FHdbj9+gHjLiQZ3zUpxsv+GZkAM0/7R0e9ov+HCfbsF/3mlsU6psrQLfOIRJQs=
