name: PyPi Upload

on:
  release:
    types: [created]

jobs:
  deploy-sdist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r dev-requirements.txt
    - name: Create sdist
      run: |
        python setup.py sdist
    - name: Copy files
      run: |
        mkdir output
        cp dist/*.tar.gz output
    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.8.6
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: output/

  deploy-manylinux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r dev-requirements.txt
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.7.1-manylinux2014_x86_64
      with:
        python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311'
        system-packages: 'libdrm-devel'
        build-requirements: 'cython'
    - name: Copy files
      run: |
        mkdir output
        cp dist/*-manylinux*.whl output
    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.8.6
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: output/

  deploy-musllinux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -r dev-requirements.txt
    - name: Build musllinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.7.1-musllinux_1_1_x86_64
      with:
        python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310 cp311-cp311'
        pre-build-command: 'apk add libdrm-dev'
        build-requirements: 'cython'
    - name: Copy files
      run: |
        mkdir output
        cp dist/*-musllinux*.whl output
    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.8.6
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: output/
